CREATE TABLE IF NOT EXISTS project_worker (
    PROJECT_ID INT NOT NULL,
    WORKER_ID INT NOT NULL,
    PRIMARY KEY (PROJECT_ID, WORKER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID)
);